version = 1

# Source Code
[[annotations]]
path = [
	"init.lua",
]
SPDX-FileCopyrightText = [
    "2019 Piezo_",
    "2026 mt-mods contributors"
]
SPDX-License-Identifier = "GPL-3.0-or-later"

# Media files
[[annotations]]
path = [
    "locale/**",
    "textures/**",
    "screenshot.png",
]
SPDX-FileCopyrightText = [
    "2019 Piezo_",
    "2026 mt-mods contributors"
]
SPDX-License-Identifier = "CC-BY-SA-4.0"

# Metadata/config files
[[annotations]]
path = [
    ".luacheckrc",
    ".github/**",
    ".gitattributes",
    ".cdb.json",
    "README.md",
    "API.md",
    "mod.conf",
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"